title: 2020 Presidential Election Blog!
email: gracek1459@gmail.com
description: This election blog was built for my Gov 1347 course to follow the changes and record my predictions of how the election will result in November.
github_username: gkim65
theme: jekyll-theme-architect
